language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
- ./ci/benchmark.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "vQ1lWJJ6fCLLumJhP4KF+S+QP7yb1ezFFkck8DF7vGyYLs8yokCjmlQiEMjdBcTZFyjrsN7bggXpmpxptrJArWZ5edvrLiawvaPx+/Mpy5ohdl8Q0zim6gzDxS2KLgSXhp4hQEqvKJHDkTSG4a11LX4DGMPrJL8unP1yOPK5BwHtZ7ql9BGo0gQYKxpM1ly4rrlBx6iMjxlC5LXI10OTlLZYC0hJFNGSu0F1L/9UsLIek50j3uE5S6HjEFCsWr8F/PshbQCg2+rkc/LgNOdkwkj1FT5wyRPP208pEG5QUG7Y3dJCdEKZ5yaz19ynI5yEP6TxmMUrRUQkRj8EpV9QhYCrZX4bbkyhfkxy+Wc59rnPUGZpd8KeOOhBgtelYtYKNnb/G+q3lqs9d6ItwU+qsfwPKtKJvyCqR3TxM/+1s47vtCYpsYRg4X2Fmp3FnGc8iU35Pll7G7xR9axeFneueXGuwAhYpdwJEqtVk9l7avXL4sSJ9fDowziC/wDp7SsFNnrwwXYsg48cFusygE0qV3/0iK61ZhC6TLcL2POvpX1r6hakg8CC50JjnFRn4exppRiuqUqFgJIejdRlagIYmZFcjoxcX29enD/sCjLQ3LK3wRjMbD/HADUphYR6h1ck/FPYPrcIVz2hUgKX9vmN5q9oefBVWMexm84x68K5xiE="
env:
  secure: "J7h4c9eP7GttBCil2HHkC6Ktrgct0PxptwLNLKYTix9QaRdbzigGOIu0uE5lMkt6ous50C8N3zFSKLkSh0bDIWW47FGlhoTJ2OhYK3TTQj19Fw49M7hW1SYcV5CvtuPeJNC7zkV3AP+ipeMbzKNTHr5KxUerhplvHk11u2FGV2E2IRrTWMQX2UIh8AerucirSs441FivYjzGSFSCjVCr5fY8npSK0XoWfsV5J26gZpVIcI05qg37+9TZ8/7nBQTDESGdXusY+QCfvgD5aOctHeeX+wwnY6Bdji1HZO3qHyC1qkretKEDtIADopWdpDi6Po99N62VOCo2lLd1Hfr7YR7/cPc9UPHWs3wC+Zhhx3ejnCpWdxUbbDDX4xNpDJUjopKpW+AutnQgoTOxpfQmrMGTNEjgrrYtz7ZYVL5L2UYVrZ30rvK6IvJfpMcYOAd3uubttWl2VzfA2vwcWpesJQsSshQ8mGei55/PA/lE4aeXSLyeLQ35WHNajs8uyeGxolr1pvDu0b7b0oOeqSST/VbpOn/TAq1e3oMjCQcjkQiJk79iWWXe0Kbkq5yoL2NiZcjpyAUpTBHzQCGPSMNCzLznrVcLPucL8Ty3v7GCL/mevyA2sz5iBplIIzf/TN/Jcyqg4uWfnKAhA0RVIVI+kH43636cciujniQe/vUHvyE="
