language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "vQ1lWJJ6fCLLumJhP4KF+S+QP7yb1ezFFkck8DF7vGyYLs8yokCjmlQiEMjdBcTZFyjrsN7bggXpmpxptrJArWZ5edvrLiawvaPx+/Mpy5ohdl8Q0zim6gzDxS2KLgSXhp4hQEqvKJHDkTSG4a11LX4DGMPrJL8unP1yOPK5BwHtZ7ql9BGo0gQYKxpM1ly4rrlBx6iMjxlC5LXI10OTlLZYC0hJFNGSu0F1L/9UsLIek50j3uE5S6HjEFCsWr8F/PshbQCg2+rkc/LgNOdkwkj1FT5wyRPP208pEG5QUG7Y3dJCdEKZ5yaz19ynI5yEP6TxmMUrRUQkRj8EpV9QhYCrZX4bbkyhfkxy+Wc59rnPUGZpd8KeOOhBgtelYtYKNnb/G+q3lqs9d6ItwU+qsfwPKtKJvyCqR3TxM/+1s47vtCYpsYRg4X2Fmp3FnGc8iU35Pll7G7xR9axeFneueXGuwAhYpdwJEqtVk9l7avXL4sSJ9fDowziC/wDp7SsFNnrwwXYsg48cFusygE0qV3/0iK61ZhC6TLcL2POvpX1r6hakg8CC50JjnFRn4exppRiuqUqFgJIejdRlagIYmZFcjoxcX29enD/sCjLQ3LK3wRjMbD/HADUphYR6h1ck/FPYPrcIVz2hUgKX9vmN5q9oefBVWMexm84x68K5xiE="
