language: node_js
services:
- mysql
compiler: gcc
dist: trusty

node_js:
- '8'
before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "J7h4c9eP7GttBCil2HHkC6Ktrgct0PxptwLNLKYTix9QaRdbzigGOIu0uE5lMkt6ous50C8N3zFSKLkSh0bDIWW47FGlhoTJ2OhYK3TTQj19Fw49M7hW1SYcV5CvtuPeJNC7zkV3AP+ipeMbzKNTHr5KxUerhplvHk11u2FGV2E2IRrTWMQX2UIh8AerucirSs441FivYjzGSFSCjVCr5fY8npSK0XoWfsV5J26gZpVIcI05qg37+9TZ8/7nBQTDESGdXusY+QCfvgD5aOctHeeX+wwnY6Bdji1HZO3qHyC1qkretKEDtIADopWdpDi6Po99N62VOCo2lLd1Hfr7YR7/cPc9UPHWs3wC+Zhhx3ejnCpWdxUbbDDX4xNpDJUjopKpW+AutnQgoTOxpfQmrMGTNEjgrrYtz7ZYVL5L2UYVrZ30rvK6IvJfpMcYOAd3uubttWl2VzfA2vwcWpesJQsSshQ8mGei55/PA/lE4aeXSLyeLQ35WHNajs8uyeGxolr1pvDu0b7b0oOeqSST/VbpOn/TAq1e3oMjCQcjkQiJk79iWWXe0Kbkq5yoL2NiZcjpyAUpTBHzQCGPSMNCzLznrVcLPucL8Ty3v7GCL/mevyA2sz5iBplIIzf/TN/Jcyqg4uWfnKAhA0RVIVI+kH43636cciujniQe/vUHvyE="
